/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatGPT: typeof import('./src/components/ChatGPT.vue')['default']
    ChatgptIndex: typeof import('./src/components/ChatgptIndex.vue')['default']
    ChatgptTest: typeof import('./src/components/ChatgptTest.vue')['default']
    ChatIndex: typeof import('./src/components/ChatIndex.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    WeChat: typeof import('./src/components/WeChat.vue')['default']
  }
}
